$(document).ready(function() {
  // LIBRARIES CODE
  LibVars = {};
  // PROJECT CODE
  var _that = this;
  // Block#: 1
  function on_Button_click(e) {
    try {
      // Block#: 6
      com.fc.JavaScriptDistLib.Image.setProperty["Alpha"]("Image", (com.fc.JavaScriptDistLib.Image.getProperty["Alpha"]("Image") * 100 - 10)); // Block#: 4
      com.fc.JavaScriptDistLib.Label.setProperty["Text"]("Label", (String('Button 1      ') + String(com.fc.JavaScriptDistLib.Image.getProperty["Alpha"]("Image") * 100)));
      e.stopPropagation();
    } catch(e) {
      com.fc.JavaScriptDistLib.handleExceptionNative(e);
    }
  };
  $('[obj-name="Button"]').on('click', on_Button_click);
  // Block#: 8
  function on_Button2_click(e) {
    try {
      // Block#: 13
      com.fc.JavaScriptDistLib.Image.setProperty["Alpha"]("Image", (com.fc.JavaScriptDistLib.Image.getProperty["Alpha"]("Image") * 100 + 10)); // Block#: 11
      com.fc.JavaScriptDistLib.Label.setProperty["Text"]("Label", (String('Button 2      ') + String(com.fc.JavaScriptDistLib.Image.getProperty["Alpha"]("Image") * 100)));
      e.stopPropagation();
    } catch(e) {
      com.fc.JavaScriptDistLib.handleExceptionNative(e);
    }
  };
  $('[obj-name="Button2"]').on('click', on_Button2_click);
  $('[obj-name="MainScreen"]').show();
});
// Generated by snapp
// 309187-505926-799906-674769
